'use strict'

module.exports = {
  registry: 'Раздел Ведение реестров ПД_web',
  rolesSection: 'Раздел Справочник ролей пользователей_web',
  role: 'Список ролей',
  usersSection: 'Раздел Управление пользователями_web',
  user: 'Список пользователей',
  systemLogSection: 'Раздел Системный журнал_web',
  rosreestrOksSection: 'Раздел Реестр ОКС по данным Росреестра_web',
  rosreestrOks: 'Запись ОКС Росреестра',
  smevRequestSection: 'Раздел Журнал запросов_web',
  smevRequest: 'Межведомственный запрос',
  eventsCalendarSection: 'Раздел Календарь событий',
  eventsModule: 'Модуль События',
  event: 'Событие',
  report: 'Отчет',
  settingsProfile: 'Раздел Профили настроек территориальных служб_web',
  addressRegistryObject: 'Объект адресного реестра',
  analytics: 'Аналитика пользователя',
  analyticsModule: 'Модуль Анализ',
  librarySection: 'Раздел Библиотека_web',
  systemParametersSection: 'Раздел Общесистемные настройки_web',
  isogdDocument: 'Документ Книги регистрации',
  storageBook: 'Книга хранения',
  registrationBook: 'Книга регистрации документов',
  steadFileBook: 'Дело о ЗУ',
  textPart: 'Карточка текстовой части',
  textPartFileInfo: 'Карточка файла текстовой части',
  spatialDataRd: 'Пространственные данные книг регистрации/хранения',
  layersGroup: 'Группа слоёв',
  layer: 'Слои',
  section: 'Подраздел отраслевого интерфейса',
  module: 'Отраслевой интерфейс',
  spatialDataCatalogModule: 'Модуль Каталог ПД',
  georesourcesCatalog: 'Раздел Каталог георесурсов_web',
  spatialDataPd: 'Пространственные данные каталога ПД',
  registryAdministration: 'Раздел Реестры ПД_web',
  fnsSteadRegistry: 'Реестр ЗУ ФНС',
  spatialDataRegistry: 'Реестр пространственных данных',
  analyticsEdit: 'Подготовка аналитических отчетов_web',
  lkpMo: 'ЛКП. Отчетность ОМСУ',
  lkpWaste: 'ЛКП. Кадастровых отходов',
  lkpKha: 'Протоколы КХА',
  lkTechnogen: 'ЛК. Техногенная нагрузка',
  isogd: 'ИСОГД_web',
  requests: 'Заявка',
  developedDocument: 'Разрабатываемый документ_web',
  developedDocumentType: 'Справочник Виды разрабатываемых документов_web',
  requestResponse: 'Ответ на заявку',
  terrZoneSection: 'Реестр территориальных зон_web',
  terrZone: 'Реестр зон',
  urbanPlanningRegulation: 'Градостроительный регламент',
  advertisingConstruction: 'Рекламная конструкция',
  specialZone: 'ЗОУИТ_web',
  reportTemplate: 'Шаблон отчета',
  volume: 'Том',
  ISOGDDocument: 'Документ ГД_web',
  // Справочники
  administrativeDocumentsTypes: 'Виды распорядительных документов',
  presentationFormsClassifier: 'Классификатор форм представления документов',
  ISOGDSections: 'Разделы ИСОГД_web',
  recordBookDocumentStatus: 'Статус документа книги учета сведений',
  GDEngineTypes: 'Типы машинного носителя ГД',
  ISOGDBookTypes: 'Типы книг ИСОГД',
  usageViews: 'Виды использования',
  measurementUnits: 'Единицы измерений',
  usageTypes: 'Типы использования',
  circulationChannels: 'Каналы обращения',
  requestResponseResult: 'Результат исполнения в ответе на заявку',
  requestStatuses: 'Статусы заявки',
  requestApplicantTypes: 'Типы заявителей',
  requestTypes: 'Типы заявок',
  oksObjectTypes: 'Тип объекта ОКС',
  urbanPlanningTypes: 'Типы субъектов ГД',
  documentIssuedStatus: 'Статусы выдаваемых документов',
  isogdDocumentsClassifier: 'Классификатор документов',
  isogdStorageBookTypes: 'Типы книг хранения ИСОГД',
  terzoneClassifierTypes: 'Классификатор типов территориальных зон/подзон',
  constructionParameters: 'Параметры строительства',
  developedDocumentsViews: 'Справочник Виды разрабатываемых документов_web',
  oktmo: 'ОКТМО',
  GDSubjects: 'Субъекты ГД',
  ISOGDService: 'Службы ИСОГД',
  tuningTableDocuments: 'Настроечная таблица Видов документов и Субъектов ГД',
  thematicSection: 'Тематические разделы',
  isogdFileFormat: 'Справочник форматов',
  documentAdjustment: 'Согласование документа'
  //
}
